"""add user passwords

Revision ID: 9c4d2c836d05
Revises: 18af853fc5c4
Create Date: 2026-08-14 04:36:48.734906

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9c4d2c836d05'
down_revision: str | None = '18af853fc5c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
