"""Turning a recorded run into a set of stops that already know their answer.

The simulated plants script their own breakdowns, changeovers, micro-stops
and idling, so the true reason for every stop in a recorded run is written
down in the file the generator obeyed. These tests are about turning that
into an evaluation set without any of the four ways it could quietly become
worthless: a label read from something the question can also see, a window
that includes seconds the MES never had, a set of nothing but positives, and
a set that changes between two runs of the same code.

Nothing here opens a network, asks anything of any model, or starts a plant.
The fixture run is in the repository: `tests/fixtures/labelled-run`, four
stations and four hundred seconds, generated by this package's own
generator.
"""

import json
from pathlib import Path

import pytest

from fsmes.sim import generate, labelled

RUN = Path(__file__).parent / "fixtures" / "labelled-run"
EXPECTED = Path(__file__).parent / "fixtures" / "labelled-set.json"

#: The one window whose state text the fixture keeps in full, so a person
#: reading the fixture can see what a question is actually asked over.
FULLY_KEPT = "labelled-run/bench/WLD01/100"


@pytest.fixture(scope="module")
def built() -> dict:
    return labelled.build_many([RUN])


def a_record(built: dict, identifier: str) -> dict:
    for record in built["records"]:
        if record["id"] == identifier:
            return record
    raise AssertionError(f"{identifier} is not in the set")


# ------------------------------------------------- the set does not drift

def test_the_same_run_always_produces_the_same_set(built):
    """Two builds of one run are the same set, down to the characters.

    A calibration is a measurement against a set. If the set can change
    while the runs it came from do not, last month's number and this
    month's are not comparable and nobody can tell that they are not.
    """
    again = labelled.build_many([RUN])
    assert again["records"] == built["records"]
    assert again["totals"] == built["totals"]


def test_the_set_is_still_the_one_the_fixture_recorded(built):
    """The whole set, against the copy in the repository.

    The state text is compared by its hash for every window but one, and in
    full for that one: a hash catches the drift, and the window kept in full
    means a person can see what drifted without running anything.
    """
    expected = json.loads(EXPECTED.read_text(encoding="utf-8"))
    rebuilt = json.loads(json.dumps(built))
    for record in rebuilt["records"]:
        if record["id"] != FULLY_KEPT:
            record.pop("state")
    assert rebuilt["records"] == expected["records"]
    assert rebuilt["totals"] == expected["totals"]
    assert rebuilt["vocabulary"] == expected["vocabulary"]


def test_the_fixture_run_is_still_what_the_generator_writes(tmp_path):
    """The recorded CSVs, against the generator replaying the same description.

    The fixture is a recorded run, not a hand-typed table, and this is what
    keeps it one: change the generator and this fails, rather than the set
    silently describing a plant this repository no longer simulates.
    """
    config = generate.load_config(RUN / "line" / "bench.json")
    generate.write_output(config, generate.simulate(config), tmp_path)
    recorded = sorted(p.name for p in (RUN / "replay" / "bench").iterdir())
    assert sorted(p.name for p in tmp_path.iterdir()) == recorded
    for name in recorded:
        # Line by line rather than byte for byte: Windows is a first-class
        # target here, and on a Windows checkout both the line ending git
        # hands back and the one `write_text` puts down can be CRLF. What
        # this test is for is a change in the rows, not in the newlines.
        assert (tmp_path / name).read_text(encoding="utf-8").splitlines() == \
            (RUN / "replay" / "bench" / name).read_text(encoding="utf-8").splitlines(), \
            f"{name} is not what the generator writes any more"


# ------------------------------------------------------- where labels come from

def test_a_scripted_breakdown_is_labelled_as_one_and_says_which_event(built):
    record = a_record(built, "labelled-run/bench/WLD01/100")
    assert record["label"] == "breakdown"
    assert record["scripted"] is True
    assert "scripted `down` for Weld from 100s to 160s" in record["label_says"]


def test_a_changeover_is_a_planned_stop_and_is_labelled_apart_from_a_breakdown(built):
    """The one mapping decision with real consequences, in the labels too.

    A changeover called a breakdown destroys every availability figure the
    plant reports. A set that cannot tell them apart cannot measure whether
    anything else can.
    """
    changeovers = [r for r in built["records"] if r["label"] == "changeover"]
    assert changeovers, "the fixture scripts a changeover"
    assert all(r["scripted"] for r in changeovers)
    assert all("changeover" in r["label_says"] for r in changeovers)


def test_a_stop_the_line_s_own_buffers_produced_is_labelled_and_marked_unscripted(built):
    """A knock-on starve is a real stop with a real reason that nobody wrote
    down in advance. It is kept, labelled, and marked as not scripted, so a
    reader can see how much of the set is emergent rather than staged."""
    emergent = [r for r in built["records"]
                if r["label"] in ("starved", "blocked") and not r["scripted"]]
    assert emergent, "a four-station line with buffers produces these"
    assert all("nobody scripted this one" in r["label_says"] for r in emergent)


def test_a_window_with_no_stop_in_it_is_in_the_set_as_a_control(built):
    """A set of nothing but stops cannot show a reason being invented.

    Round 5 raised exactly that: one condition scored highest on every run,
    including the six where nothing of the kind happened. Controls are how
    the next measurement can see it.
    """
    controls = [r for r in built["records"] if r["label"] == "none"]
    assert controls
    assert all("ran through this window" in r["label_says"] for r in controls)
    assert all("was running for the whole window" in r["state"] for r in controls)


def test_a_counter_reset_is_labelled_where_the_hour_scripts_one(built):
    reset = [r for r in built["records"] if r["label"] == "counter_reset"]
    assert len(reset) == 1
    assert "scripted `counter_reset` for Press at 200s" in reset[0]["label_says"]


def test_a_stop_too_short_to_name_is_not_a_question(tmp_path):
    """Below the floor nothing in the truth can be named, so nothing is asked.

    The floor is stated, not hidden: it is written into the set's settings
    and it can be moved from the command line.
    """
    long_enough = labelled.build_many([RUN], minimum_seconds=5)
    only_the_big_ones = labelled.build_many([RUN], minimum_seconds=100)
    assert only_the_big_ones["totals"]["records"] < long_enough["totals"]["records"]
    assert only_the_big_ones["settings"]["minimum_seconds"] == 100


# ------------------------------------- what the question is allowed to see

def test_the_state_word_is_not_in_the_window_the_question_is_asked_over(built):
    """The label is read off the machine's state word, so the window may not
    carry it: a question whose answer is printed in its own evidence
    measures nothing at all."""
    record = a_record(built, FULLY_KEPT)
    assert record["state_view"] == "stopped-not-why"
    assert "TSec,Running," in record["state"]
    assert "State" not in record["state"].split("\n\n")[1]
    assert "does not publish a reason" in record["state"]


def test_the_alarm_word_and_the_ready_bit_are_still_there(built):
    """What is withheld is the reason code and nothing else. A real diagnosis
    reads the alarm word, the ready bit and the neighbours' counters, and all
    three are exactly as the machine published them."""
    state = a_record(built, FULLY_KEPT)["state"]
    assert "AlarmWord" in state and "ReadyBit" in state
    assert "the machine before it on the line" in state
    assert "the machine after it on the line" in state


def test_the_full_view_keeps_the_state_word_so_the_difference_can_be_measured(built):
    """Some machine layers do publish a reason code. Both views are built by
    the same code, so what separates them is the reason code and nothing
    else - which makes the gap between the two measurements a number worth
    having rather than an argument."""
    full = labelled.build_many([RUN], state_view="full")
    record = a_record(full, FULLY_KEPT)
    assert record["state_view"] == "full"
    assert "TSec,State," in record["state"]
    assert "0 stopped, 1 running" in record["state"]
    assert record["label"] == a_record(built, FULLY_KEPT)["label"]


def test_an_unknown_state_view_is_refused_rather_than_guessed():
    with pytest.raises(ValueError, match="unknown state view"):
        labelled.build(RUN, state_view="whatever-you-like")


# ------------------------------------- what the MES could not see stays unseen

def test_the_seconds_the_mes_had_no_connection_for_are_cut_out_and_said(built):
    """Decision 0030: for those minutes the MES has no state at all. Handing
    the tags over anyway would be inventing observation, and writing blanks
    or the last state anybody heard would be two other ways of writing down
    something that did not happen."""
    inside = [r for r in built["records"] if r["unseen_seconds"] > 0]
    assert inside, "the fixture scripts a disconnect"
    for record in inside:
        assert "no rows from 335s to 395s" in record["state"]
        assert "no connection to the machine layer" in record["state"]


def test_a_stop_entirely_inside_a_disconnect_is_marked_unobservable(built):
    unobservable = [r for r in built["records"] if not r["observable"]]
    assert unobservable
    for record in unobservable:
        assert record["unseen_seconds"] >= record["seconds"]


# --------------------------------------------------- totals, stated as totals

def test_every_label_is_counted_even_the_ones_nothing_carries(built):
    """A label with no examples is a thing this set cannot measure. It can
    only say so by being printed as zero rather than left out."""
    counted = built["totals"]["by_label"]
    assert list(counted) == list(labelled.REASON_NAMES)
    assert sum(counted.values()) == built["totals"]["records"]


def test_the_set_states_how_big_its_questions_are(built):
    """What a pass will cost is a property of the set, and it is stated in
    the set rather than worked out later from the bill."""
    sizes = built["totals"]["state_characters"]
    assert sizes["smallest"] <= sizes["median"] <= sizes["largest"]
    assert sizes["total"] == sum(
        r["state_characters"] for r in built["records"])


def test_the_scorecard_s_own_verdict_is_carried_beside_the_label(built):
    """What the MES already decided about the window, so a reader can see
    where the deterministic answer and a proposal disagree without going
    back to the run."""
    record = a_record(built, FULLY_KEPT)
    assert record["mes_verdict"]["kind"] == "faults"
    assert record["mes_verdict"]["observed"] is True
    assert "faults[0]" in record["mes_verdict_says"]


def test_a_window_the_scorecard_names_nothing_in_says_so_rather_than_nothing(built):
    """Unknown is not zero: a window with no scored event is a window the
    scorecard was never asked about, and the record says which."""
    emergent = next(r for r in built["records"] if not r["scripted"])
    assert emergent["mes_verdict"] is None
    assert "names no scripted event" in emergent["mes_verdict_says"]


def test_a_run_with_no_line_description_is_skipped_with_a_note(tmp_path):
    """A results directory that kept its replay but not the description the
    generator obeyed has no truth in it, so it contributes nothing - and
    says so, rather than contributing unlabelled windows nobody notices."""
    import shutil

    copied = tmp_path / "half-a-run"
    shutil.copytree(RUN, copied)
    (copied / "line" / "bench.json").unlink()
    built = labelled.build_many([copied])
    assert built["totals"]["records"] == 0
    assert built["runs"][0]["notes"]
    assert "no line description" in built["runs"][0]["notes"][0]
