"""initial schema

Revision ID: 18af853fc5c4
Revises:
Create Date: 2026-08-13 21:37:33.603480

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '18af853fc5c4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Enum('enterprise', 'site', 'area', 'work_center', 'work_unit', name='equipmentlevel', native_enum=False, length=30), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ideal_cycle_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_code'), ['code'], unique=True)

    op.create_table('erp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='messagedirection', native_enum=False, length=30), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'processed', 'error', name='messagestatus', native_enum=False, length=30), nullable=False),
    sa.Column('error', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('erp_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_messages_status'), ['status'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('raw', 'intermediate', 'finished', name='materialtype', native_enum=False, length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_code'), ['code'], unique=True)

    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'component_id')
    )
    op.create_table('equipment_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('running', 'idle', 'down', 'setup', name='equipmentstatename', native_enum=False, length=30), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_states', schema=None) as batch_op:
        batch_op.create_index('ix_equipment_states_eq_started', ['equipment_id', 'started_at'], unique=False)

    op.create_table('quality_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('characteristic', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'characteristic')
    )
    op.create_table('routings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tag_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_values', schema=None) as batch_op:
        batch_op.create_index('ix_tag_values_tag_ts', ['tag', 'ts'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'released', 'running', 'completed', 'closed', 'cancelled', name='orderstatus', native_enum=False, length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('erp_reference', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_orders_status'), ['status'], unique=False)

    op.create_table('material_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('original_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('available', 'exhausted', 'blocked', name='lotstatus', native_enum=False, length=30), nullable=False),
    sa.Column('produced_by_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['produced_by_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_lots_code'), ['code'], unique=True)

    op.create_table('quality_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('result', sa.Enum('pass', 'fail', name='checkresult', native_enum=False, length=30), nullable=False),
    sa.Column('checked_by', sa.String(length=40), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['quality_specs.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_checks_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('routing_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_id', 'seq')
    )
    op.create_table('work_order_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', name='operationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('good_qty', sa.Float(), nullable=False),
    sa.Column('scrap_qty', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_id', 'seq')
    )
    op.create_table('lot_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['material_lots.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lot_consumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_consumptions_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_consumptions_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('non_conformances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='ncstatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['material_lots.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('production_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('good_qty', sa.Float(), nullable=False),
    sa.Column('scrap_qty', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'opc', name='productionsource', native_enum=False, length=30), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['work_order_operations.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_logs_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_logs_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_logs_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_logs_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_production_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_production_logs_equipment_id'))

    op.drop_table('production_logs')
    op.drop_table('non_conformances')
    with op.batch_alter_table('lot_consumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_consumptions_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_lot_consumptions_lot_id'))

    op.drop_table('lot_consumptions')
    op.drop_table('work_order_operations')
    op.drop_table('routing_operations')
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_checks_work_order_id'))

    op.drop_table('quality_checks')
    with op.batch_alter_table('material_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_lots_code'))

    op.drop_table('material_lots')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_status'))
        batch_op.drop_index(batch_op.f('ix_work_orders_code'))

    op.drop_table('work_orders')
    with op.batch_alter_table('tag_values', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_values_tag_ts')

    op.drop_table('tag_values')
    op.drop_table('routings')
    op.drop_table('quality_specs')
    with op.batch_alter_table('equipment_states', schema=None) as batch_op:
        batch_op.drop_index('ix_equipment_states_eq_started')

    op.drop_table('equipment_states')
    op.drop_table('bom_items')
    op.drop_table('personnel')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_code'))

    op.drop_table('materials')
    with op.batch_alter_table('erp_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_messages_status'))

    op.drop_table('erp_messages')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_code'))

    op.drop_table('equipment')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
