"""The simulation surface, exposed as MCP tools.

This is how the simulator is meant to be driven: conversationally. "Run the
machining plant with the mill down twice as long and tell me whether the MES
still catches it" is a sentence, not a script.

Two rules shape everything here.

The tools are thin. All of the intelligence lives in fsmes.sim, where it can
be tested without an agent in the loop; a tool is argument parsing and a call.
When a tool starts making decisions, that logic belongs in the engine.

And the simulation only ever reaches the MES through its public API and OPC UA
- never its database. That is deliberate: every scenario run through here also
exercises the surface an agent would use, so a gap in that surface shows up as
a scenario nobody can express rather than as a weakness nobody notices.

Long work does not block a conversation. A scored run takes about a minute and
a sweep takes several, so those tools start a job and hand back an id; ask
job_status for the outcome.
"""

from __future__ import annotations

import csv
import json
import os
import threading
import traceback
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from mcp.server.mcpserver import MCPServer

from fsmes import plant as plants
from fsmes.sim import store
from fsmes.sim import sweep as sweep_mod
from fsmes.sim.generate import generate
from fsmes.sim.runner import scored_run
from fsmes.sim.truth import load_truth

mcp = MCPServer(
    name="fsmes-sim",
    instructions=(
        "Drive the FactorySemantics MES simulation fleet: describe plants, run "
        "scored simulations against known ground truth, sweep parameters, and "
        "read the trend across past runs. Scoring answers 'did the MES tell the "
        "truth about the plant?' - production booked versus produced, planned "
        "stops not counted as downtime, breakdowns detected. Scored runs and "
        "sweeps are asynchronous: they return a job id for job_status."
    ),
)

# See fsmes.mcp_server: FSMES_ROOT names the checkout this server drives.
ROOT = plants.find_root(Path(os.environ.get("FSMES_ROOT")
                             or Path.home() / "Projects" / "factorysemantics-mes"))
DATASETS = Path.home() / ".local" / "share" / "fsmes" / "datasets"

_jobs: dict[str, dict] = {}
_lock = threading.Lock()


def _registry() -> dict[str, dict]:
    return plants.load_registry(ROOT)


def _line_for(name: str, cfg: dict) -> Path:
    return ROOT / Path(cfg["replay_dir"]).parent / "line.json"


def _start(kind: str, target: str, work) -> dict:
    """Run `work` on a thread, tracked by id."""
    job_id = f"{kind}-{uuid.uuid4().hex[:8]}"
    record = {"job": job_id, "kind": kind, "target": target, "state": "running",
              "started_at": datetime.now(UTC).isoformat(), "log": []}
    with _lock:
        _jobs[job_id] = record

    def echo(line: str) -> None:
        with _lock:
            record["log"].append(str(line))

    def run() -> None:
        try:
            result = work(echo)
            with _lock:
                record.update(state="done", result=result,
                              finished_at=datetime.now(UTC).isoformat())
        except Exception as exc:
            with _lock:
                record.update(state="failed", error=f"{type(exc).__name__}: {exc}",
                              traceback=traceback.format_exc()[-2000:],
                              finished_at=datetime.now(UTC).isoformat())

    threading.Thread(target=run, daemon=True).start()
    return {"job": job_id, "state": "running",
            "note": f"Ask job_status('{job_id}') in a minute or so."}


# --------------------------------------------------------------- describing

@mcp.tool()
def list_plants() -> dict:
    """The simulated plants available, and whether each can be scored.

    A plant is scoreable only if its line is described by a line.json - the
    scorer compares against ground truth it can read, so a line generated by
    code rather than data cannot be measured.
    """
    out = []
    for name, cfg in _registry().items():
        line = _line_for(name, cfg)
        out.append({
            "plant": name,
            "label": cfg.get("label"),
            "dashboard": plants.dashboard_url(cfg),
            "scoreable": line.is_file(),
            "line_description": str(line) if line.is_file() else None,
        })
    return {"plants": out}


@mcp.tool()
def describe_line(plant: str) -> dict:
    """What a plant's line is and what the simulator does to it.

    The events are ground truth: the generator obeyed them, so they are what
    the MES should have seen.
    """
    registry = _registry()
    if plant not in registry:
        return {"error": f"Unknown plant {plant!r}. Known: {', '.join(registry)}."}
    cfg = registry[plant]
    line = _line_for(plant, cfg)
    if not line.is_file():
        return {"error": f"{plant} has no line.json, so it has no readable ground truth.",
                "expected_at": str(line)}
    truth = load_truth(line, ROOT / cfg["tag_map"])
    return {
        "plant": plant,
        "label": cfg.get("label"),
        "duration_s": truth["duration_s"],
        "seed": truth["seed"],
        "stations": truth["stations"],
        "equipment": truth["equipment"],
        "events": [
            {"type": e.type, "station": e.station, "equipment": e.equipment,
             "start_s": e.start_s, "end_s": e.end_s,
             "planned": e.planned, **e.detail}
            for e in truth["events"]
        ],
    }


@mcp.tool()
def list_knobs() -> dict:
    """What a sweep is allowed to vary, and why only these.

    Variance is applied to the line, never to the MES's own models - a
    simulator that shares the product's assumptions cannot catch the product's
    blind spots. So the knobs are physical.
    """
    return {"knobs": sweep_mod.KNOBS,
            "station_scope": "Pass station= to apply a station-level knob to one machine."}


# ------------------------------------------------------------------ running

@mcp.tool()
def score_plant(plant: str, speed: float = 60.0) -> dict:
    """Run a plant through its scripted hour and score what it reported.

    Asynchronous - returns a job id. At speed 60 a 3600 s line hour takes about
    a minute of wall clock. The runner picks an OPC sampling interval fast
    enough to see the briefest scripted event at that speed, so a short event
    is not scored as missed when it was merely never sampled.
    """
    registry = _registry()
    if plant not in registry:
        return {"error": f"Unknown plant {plant!r}. Known: {', '.join(registry)}."}
    cfg = registry[plant]

    def work(echo):
        card = scored_run(plant, cfg, ROOT, speed, echo=echo)
        run_id = store.record(card)
        return {"run_id": run_id, "metrics": card["metrics"],
                "observation": card["observation"],
                "faults": card["faults"], "planned_stops": card["planned_stops"]}

    return _start("score", plant, work)


@mcp.tool()
def sweep_plant(plant: str, knobs: dict[str, list], station: str | None = None,
                speed: float = 60.0) -> dict:
    """Vary a line, score every variant, and compare the results.

    knobs is {knob: [values]}, expanded into the cartesian product - e.g.
    {"buffer_capacity": [2, 6, 20]} runs three variants. Ask list_knobs for
    what can be varied.

    Asynchronous, and each variant costs roughly a minute at speed 60, so a
    six-point sweep is a six-minute job.
    """
    registry = _registry()
    if plant not in registry:
        return {"error": f"Unknown plant {plant!r}. Known: {', '.join(registry)}."}
    cfg = registry[plant]
    base = _line_for(plant, cfg)
    if not base.is_file():
        return {"error": f"{plant} has no line.json and cannot be swept."}

    grid = dict(knobs)
    if station:
        grid["_station"] = station
    try:
        variants = sweep_mod.expand(grid)
    except KeyError as exc:
        return {"error": str(exc).strip('"')}

    def work(echo):
        import tempfile
        workdir = Path(tempfile.mkdtemp(prefix=f"fsmes-mcp-sweep-{plant}-"))
        cards = []
        for index, variant in enumerate(variants, 1):
            text = sweep_mod.label(variant)
            echo(f"[{index}/{len(variants)}] {text}")
            line = sweep_mod.write_variant(base, variant, workdir / f"v{index}.json")
            data = workdir / f"v{index}-out"
            generate(line, data, write_docs=False)
            point = dict(cfg, replay_dir=str(data))
            card = scored_run(plant, point, ROOT, speed, line_json=line, echo=echo)
            card["variant"] = text
            store.record(card, variant={k: v for k, v in variant.items()
                                        if not k.startswith("_")})
            cards.append(card)
        return sweep_mod.compare(cards)

    return _start("sweep", plant, work)


@mcp.tool()
def job_status(job: str, log_tail: int = 12) -> dict:
    """How a scored run or sweep is getting on, and its result once finished."""
    with _lock:
        record = _jobs.get(job)
        if not record:
            known = [j for j in _jobs]
            return {"error": f"No job {job!r}.",
                    "known_jobs": known[-10:] if known else "none this session"}
        out = {k: v for k, v in record.items() if k != "log"}
        out["log_tail"] = record["log"][-log_tail:]
        return out


@mcp.tool()
def list_jobs() -> dict:
    """Jobs started this session. Restarting the server forgets them; finished
    runs are still in the results store."""
    with _lock:
        return {"jobs": [{k: v for k, v in j.items() if k not in ("log", "result", "traceback")}
                         for j in _jobs.values()]}


# ------------------------------------------------------------------ reading

@mcp.tool()
def recent_runs(plant: str | None = None, limit: int = 20) -> dict:
    """Scored runs already recorded, newest first."""
    return {"runs": store.recent(plant, limit)}


@mcp.tool()
def run_scorecard(run_id: int) -> dict:
    """The full scorecard for one recorded run."""
    row = store.get(run_id)
    return row or {"error": f"No run {run_id}."}


@mcp.tool()
def metric_trend(plant: str, metric: str = "breakdown_recall", limit: int = 50) -> dict:
    """One metric across past runs, oldest first.

    This is the question a single scorecard cannot answer: not "is the MES
    honest" but "is it getting better". Metrics: breakdown_recall,
    planned_stop_misclassified, mean_lag_sim_s.
    """
    try:
        points = store.trend(plant, metric, limit)
    except ValueError as exc:
        return {"error": str(exc)}
    values = [p["value"] for p in points if p["value"] is not None]
    return {
        "plant": plant, "metric": metric, "points": points,
        "summary": {
            "n": len(values),
            "first": values[0] if values else None,
            "latest": values[-1] if values else None,
            "best": max(values) if values else None,
            "worst": min(values) if values else None,
        } if values else {"n": 0, "note": "no scored values yet"},
    }


@mcp.tool()
def compare_runs(run_ids: list[int]) -> dict:
    """Put recorded scorecards side by side, and say what differs."""
    cards = []
    missing = []
    for run_id in run_ids:
        row = store.get(run_id)
        if not row:
            missing.append(run_id)
            continue
        card = row["scorecard"]
        card["variant"] = (row.get("variant") and json.dumps(row["variant"])) or card.get("variant")
        cards.append(card)
    if not cards:
        return {"error": f"None of those runs exist: {run_ids}"}
    out = sweep_mod.compare(cards)
    if missing:
        out["missing"] = missing
    return out


# ---------------------------------------------------------------- ingestion

@mcp.tool()
def ingest_dataset(path: str, name: str | None = None) -> dict:
    """Profile a CSV of real records so a scenario can be built from its shape.

    Reads the file, describes every column - type, range, distinct values -
    and keeps the profile under a name a later tool can reach.

    Honest about what happens next: the profile is stored, but the generators
    that turn a dataset into a scenario currently cover work orders, downtime
    and quality, because those are the modules the MES has. Maintenance and
    scheduling data can be profiled and kept, and cannot yet be simulated
    against, because there is no maintenance module to feed.
    """
    source = Path(path).expanduser()
    if not source.is_file():
        return {"error": f"No file at {source}."}
    if source.suffix.lower() in (".xlsx", ".xls"):
        return {"error": "Excel is not readable here yet - export the sheet as CSV.",
                "why": "openpyxl is not a dependency of the MES, and adding one to "
                       "read a spreadsheet is a decision worth making deliberately."}

    with source.open(newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        return {"error": f"{source} has no data rows."}

    profile: dict[str, Any] = {}
    for column in rows[0]:
        values = [r[column] for r in rows if r.get(column) not in (None, "")]
        numeric = []
        for v in values:
            try:
                numeric.append(float(v))
            except (TypeError, ValueError):
                numeric = []
                break
        entry: dict[str, Any] = {"present": len(values), "missing": len(rows) - len(values)}
        if numeric:
            entry.update(kind="number", min=min(numeric), max=max(numeric),
                         mean=round(sum(numeric) / len(numeric), 4))
        else:
            distinct = sorted(set(values))
            entry.update(kind="text", distinct=len(distinct),
                         examples=distinct[:8])
        profile[column] = entry

    label = name or source.stem
    DATASETS.mkdir(parents=True, exist_ok=True)
    stored = DATASETS / f"{label}.json"
    stored.write_text(json.dumps(
        {"name": label, "source": str(source), "rows": len(rows),
         "columns": profile, "ingested_at": datetime.now(UTC).isoformat()},
        indent=2), encoding="utf-8")

    return {"dataset": label, "rows": len(rows), "columns": profile,
            "stored_at": str(stored),
            "next": "Scenario generation from a dataset covers work orders, "
                    "downtime and quality. Maintenance is profiled but not yet "
                    "simulatable - the MES has no maintenance module (roadmap M4)."}


@mcp.tool()
def list_datasets() -> dict:
    """Datasets ingested so far."""
    if not DATASETS.is_dir():
        return {"datasets": []}
    out = []
    for f in sorted(DATASETS.glob("*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        out.append({"name": d["name"], "rows": d["rows"],
                    "columns": list(d["columns"]), "source": d["source"]})
    return {"datasets": out}


def _allowed_hosts(host: str, port: int) -> list[str]:
    """The Host headers this server answers to: its own bind address, localhost,
    and whatever FSMES_MCP_ALLOWED_HOSTS names (comma-separated, e.g. a tailnet
    or LAN name the clients use). DNS-rebinding protection refuses the rest."""
    names = [host, "127.0.0.1", "localhost"]
    names += [h.strip() for h in os.environ.get("FSMES_MCP_ALLOWED_HOSTS", "").split(",") if h.strip()]
    out: list[str] = []
    for name in names:
        for candidate in (name, f"{name}:{port}"):
            if candidate not in out:
                out.append(candidate)
    return out


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Serve the fsmes simulation tools over MCP.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8300)
    args = parser.parse_args()

    from mcp.server.transport_security import TransportSecuritySettings

    # Bound to one address; any other name clients use for this host goes in
    # FSMES_MCP_ALLOWED_HOSTS, or DNS-rebinding protection refuses them.
    security = TransportSecuritySettings(
        allowed_hosts=_allowed_hosts(args.host, args.port),
        allowed_origins=["*"],
    )
    import anyio
    anyio.run(lambda: mcp.run_streamable_http_async(
        host=args.host, port=args.port, transport_security=security))


if __name__ == "__main__":
    main()
