#!/usr/bin/env python3
"""Read plant-shape.toml back in plain words, so a person can check it.

The file is the thing that leaves the building, so somebody has to read it, and
nobody should have to read TOML to do that. This prints what the file says, in
the order a plant engineer would ask it:

    what this says it measured — how many machines and how fast — what every tag
    looks like — how the line stops and why — quality — orders and shifts — how
    they number their paperwork — what they talk to the ERP about — and what
    their MES tracks that FactorySemantics does not.

Run it:

    python scripts/explain.py plant-shape.toml
    python scripts/explain.py plant-shape.toml --tags      # every tag, not a summary

If something here is not their plant, the mapping was wrong. Fix the mapping and
profile again; do not edit this file by hand, because the leak check only ran
against what the profiler wrote.

Python 3.11 or newer. Standard library only.
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from typing import Any


def _n(value: Any, suffix: str = "") -> str:
    """A number for a person. `not measured` stays as words."""
    if value is None or value == "not measured":
        return "not measured"
    if isinstance(value, float):
        text = f"{value:,.2f}".rstrip("0").rstrip(".")
        return f"{text}{suffix}"
    if isinstance(value, int):
        return f"{value:,}{suffix}"
    return f"{value}{suffix}"


def _pct(share: Any) -> str:
    if share is None or share == "not measured":
        return "not measured"
    return f"{float(share) * 100:.1f}%"


def _hms(seconds: Any) -> str:
    if seconds is None or seconds == "not measured":
        return "not measured"
    total = int(float(seconds))
    if total < 90:
        return f"{total} s"
    if total < 5400:
        return f"{total // 60} min {total % 60} s"
    return f"{total // 3600} h {(total % 3600) // 60} min"


def explain(shape: dict[str, Any], every_tag: bool = False) -> list[str]:
    out: list[str] = []
    say = out.append

    meta = shape.get("meta", {})
    say("What this file measured")
    say("-----------------------")
    say(f"  Written {meta.get('written_at', 'at an unknown time')} by {meta.get('written_by', 'unknown')}, "
        f"reading a {meta.get('source_dialect', 'unknown')} database, read-only.")
    say(f"  The window it looked at: {meta.get('window_start')} to {meta.get('window_end')} "
        f"({_n(meta.get('window_hours'))} hours).")
    say(f"  It read {_n(meta.get('rows_read'))} rows, bounded at {_n(meta.get('row_cap'))} per query.")
    say(f"  Of {_n(meta.get('tables_total'))} tables in that database, {_n(meta.get('tables_mapped'))} were "
        f"understood and {_n(meta.get('tables_not_understood'))} were not.")
    say(f"  Leak check: {meta.get('leak_check', 'DID NOT RUN')}")
    not_run = meta.get("queries_not_run") or shape.get("queries_not_run") or []
    if not_run:
        say(f"  {len(not_run)} query(ies) did not run:")
        for row in not_run:
            say(f"    - {row.get('query')}: {row.get('why')}")
    else:
        say("  Every query ran.")
    say("")

    plant = shape.get("plant", {})
    stations = shape.get("stations", [])
    say("The line")
    say("--------")
    say(f"  {_n(plant.get('stations_total'))} machines, in line order, named ST-01 upward. Their own codes "
        f"are not in this file.")
    for station in stations:
        tags = station.get("analogs", [])
        kinds: dict[str, int] = {}
        for tag in tags:
            kinds[tag.get("kind", "?")] = kinds.get(tag.get("kind", "?"), 0) + 1
        kind_text = ", ".join(f"{count} {kind}" for kind, count in sorted(kinds.items())) or "no tags"
        say(f"  {station.get('name')}: runs at {_n(station.get('rate_per_min'))} a minute, "
            f"scraps {_n(station.get('scrap_pct'))}% of what it makes, "
            f"ran for {_hms(station.get('running_seconds'))} in the window.")
        say(f"      made {_n(station.get('good_total'))} good and {_n(station.get('scrap_total'))} scrap; "
            f"{kind_text}.")
        if station.get("rate_per_min") in (None, "not measured"):
            say(f"      the rate is not measured: {station.get('rate_basis')}")
    say("")

    say("Every tag, and what it looks like")
    say("---------------------------------")
    say("  An analog is a measurement, a counter only goes up, a discrete is a handful of values.")
    for station in stations:
        tags = station.get("analogs", [])
        shown = tags if every_tag else [t for t in tags if t.get("kind") == "analog"]
        if not shown:
            continue
        say(f"  {station.get('name')} — {len(tags)} tags in total"
            + ("" if every_tag else f", the {len(shown)} analogs below"))
        for tag in shown:
            unit = f" {tag['unit']}" if tag.get("unit") else ""
            say(f"    {tag.get('name')} ({tag.get('kind')}): sits at {_n(tag.get('base'))}{unit}, "
                f"moves about {_n(tag.get('noise'))}{unit} around that")
            say(f"        seen between {_n(tag.get('observed_min'))} and {_n(tag.get('observed_max'))}, "
                f"a reading every {_n(tag.get('sample_interval_s'))} s, {_n(tag.get('samples'))} readings"
                + (", and it only moves while the machine runs" if tag.get("running_only") else ""))
            if tag.get("unit_dropped"):
                say("        its unit was not a unit this file carries, so it was dropped rather than copied")
    say("")

    stops = shape.get("stops", {})
    say("How the line stops")
    say("------------------")
    if not stops.get("found"):
        say(f"  Not measured. {stops.get('why', '')}")
    else:
        say(f"  {_n(stops.get('intervals_total'))} state periods over {_hms(stops.get('seconds_total'))}.")
        for state in stops.get("states", []):
            say(f"    {state.get('state'):<11} {_pct(state.get('share')):>7} of the time — "
                f"{_n(state.get('intervals'))} periods, typically {_hms(state.get('p50_seconds'))}, "
                f"longest {_hms(state.get('max_seconds'))}")
        say(f"  {_n(stops.get('stops_total'))} of those are stops somebody could put a reason against "
            f"({stops.get('stops_counted_as')}).")
        say(f"  {_n(stops.get('unlabelled_stops'))} of them — {_pct(stops.get('unlabelled_share'))} — "
            f"have no reason recorded at all. That is reported as unlabelled, not as 'other'.")
        say(f"  {stops.get('waiting_note', '')}")
        say("  The reasons they do record, as categories, with wording written by this skill to the same"
            " length as theirs:")
        for reason in stops.get("reasons", []):
            say(f"    {reason.get('category'):<12} {_pct(reason.get('share_of_stops')):>7} of stops, "
                f"{_pct(reason.get('share_of_stop_seconds')):>7} of stopped time")
            say(f"        “{reason.get('generic_wording')}”")
    say("")

    quality = shape.get("quality", {})
    say("Quality")
    say("-------")
    if not quality.get("found"):
        say(f"  Not measured. {quality.get('why', '')}")
    else:
        say(f"  {_n(quality.get('checks_total'))} checks in the window, "
            f"{_pct(quality.get('fail_share'))} of them failed.")
        say(f"  {_n(quality.get('nonconformances_total'))} non-conformances — "
            f"{_n(quality.get('nonconformances_per_1000_checks'))} per thousand checks.")
        for row in quality.get("dispositions", []):
            say(f"    {row.get('disposition'):<14} {_pct(row.get('share')):>7} of checks")
    say("")

    orders = shape.get("orders", {})
    shifts = shape.get("shifts", {})
    say("Orders and shifts")
    say("-----------------")
    if not orders.get("found"):
        say(f"  Orders not measured. {orders.get('why', '')}")
    else:
        say(f"  {_n(orders.get('orders_seen'))} orders. A typical one asks for "
            f"{_n(orders.get('qty_p50'))} and stays open {_n(orders.get('open_hours_p50'))} hours; "
            f"a big one asks for {_n(orders.get('qty_p90'))}.")
        say(f"  {_n(orders.get('still_open'))} had no close time at the moment this was read.")
    if not shifts.get("found"):
        say(f"  Shifts not measured. {shifts.get('why', '')}")
    else:
        say(f"  {_n(shifts.get('distinct_codes'))} shift codes. The pattern:")
        for row in shifts.get("pattern", []):
            say(f"    starts {row.get('starts_at_utc')} UTC, runs {_n(row.get('hours'))} hours")
    say("")

    say("How they number their paperwork")
    say("------------------------------")
    say("  A # is a digit, an A a capital letter, an a a lower-case one. No real number is in this file.")
    for row in plant.get("naming_grammar", []):
        say(f"    {row.get('what'):<24} {row.get('pattern'):<22} "
            f"{_n(row.get('seen'))} of {_n(row.get('of_total'))} seen")
    documents = shape.get("documents", {})
    if documents.get("found"):
        say(f"  {_n(documents.get('documents_seen'))} documents in their register:")
        for row in documents.get("grammar", []):
            say(f"    {row.get('pattern'):<22} {_n(row.get('seen'))} of {_n(row.get('of_total'))}")
    else:
        say(f"  Document register not measured. {documents.get('why', '')}")
    say("")

    erp = shape.get("erp", {})
    say("What it says to the ERP")
    say("-----------------------")
    if not erp.get("found"):
        say(f"  Not measured. {erp.get('why', '')}")
    else:
        say(f"  {_n(erp.get('calls_total'))} calls in the window. The endpoints' own words are not carried; "
            f"what is here is their shape.")
        for row in erp.get("touchpoints", []):
            say(f"    {row.get('verb', ''):<5} {row.get('path_shape')}")
            say(f"        {_n(row.get('calls_per_hour'))} an hour, "
                f"{_n(row.get('min_bytes'))} to {_n(row.get('max_bytes'))} bytes, "
                f"{_pct(row.get('failure_share'))} failed")
    say("")

    also = shape.get("also_tracked", [])
    note = shape.get("also_tracked_note", {})
    say("What their MES tracks that FactorySemantics does not")
    say("----------------------------------------------------")
    if not also:
        say("  Nothing — every table was understood. That is unusual; check the mapping.")
    else:
        say(f"  {len(also)} table(s), described by shape only. {note.get('why_it_matters', '')}")
        for row in also:
            say(f"    {row.get('name')}: {_n(row.get('rows_seen'))} rows, "
                f"{_n(row.get('columns_total'))} columns. Words we recognised: {row.get('words_recognised')}.")
    say("")
    say("If any of this is not your plant, the mapping was wrong. Fix the mapping and run profile.py again.")
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("shape", type=Path, help="The plant-shape.toml to read back.")
    parser.add_argument("--tags", action="store_true", help="Every tag, not just the analogs.")
    args = parser.parse_args(argv)
    shape = tomllib.loads(args.shape.read_text(encoding="utf-8"))
    print("\n".join(explain(shape, every_tag=args.tags)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
